### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [immunityinc/libptrace#2]
I would like to point out that identifiers like “[`__PT_FACTORY_H`](https://github.com/immunityinc/libptrace/blob/ad564261331e72b2cbb67103a7fb0717a96d4a8c/include/libptrace/factory.h#L41 "Update candidate")” and “[`__PYTHON_PTRACE_H`](https://github.com/immunityinc/libptrace/blob/ad564261331e72b2cbb67103a7fb0717a96d4a8c/python/ptrace.h#L43 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by rhuizer** [comment]
Thank you. This is a valid issue, I will make a pass over the header files before the next release.

**Comment by elfring** [comment]
There are [more update candidates](https://github.com/immunityinc/libptrace/blob/ad564261331e72b2cbb67103a7fb0717a96d4a8c/src/todo/libptrace_elf.c#L303 "Update candidate: ptrace_elf_get_symbol_addr()") to [consider](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?") besides include guards.

**Comment by rhuizer** [comment]
Thanks again, I enjoyed that little dive into the standard.

For reference, the project uses [C11](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf), but section 7.1.3 remains fundamentally unchanged.

It seems that for local variables changing the leading double underscore to a single underscore would be fine as a leading underscore and following lower-case letter is only reserved in file scope in the ordinary and tag name spaces.

**Comment by rhuizer** [comment]
This should have been resolved for all parts of the project that are currently built.

The problem is still present in src/linux and src/freebsd and such, but these aren't built and have only been included for me to support at a later point in time. At that point I will clean up the identifier issues in those files.
