### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [immunityinc/libptrace#3]
[Extra null pointer checks are not needed in functions](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") like the following.
- [service_list_destroy](https://github.com/immunityinc/libptrace/blob/ad564261331e72b2cbb67103a7fb0717a96d4a8c/src/windows/service.c#L127 "service_list_destroy function")
- [__update_errmsg](https://github.com/immunityinc/libptrace/blob/ad564261331e72b2cbb67103a7fb0717a96d4a8c/src/windows/error.c#L185 "__update_errmsg function")

**Comment by rhuizer** [comment]
I'm aware of this, yet it doesn't do any harm and avoids the overhead of the call, prologue construction/destruction, and the return.

Depending on the C library calling free may invoke hook functions. I admit to not having checked Windows, but as an example, [glibc](https://sourceware.org/git/?p=glibc.git;a=blob;f=malloc/malloc.c;h=7d7d30bb1363dae55bab78bd72f690a50747aa92;hb=HEAD#l3091) first check if there are hooks (an atomic read, which has a hard to quantify performance impact), if present invokes the hooks and will then check if the passed pointer is NULL. 

I see no reason to make such hook invocations, so I'm not inclined to fix this.

Thanks for submitting the issue however, as it does help to raise awareness about the standard allowing free() to handle NULL pointers.

**Comment by elfring** [comment]
I prefer to avoid redundant checks.

**Comment by rhuizer** [comment]
I agree that going by the C standard the check is redundant.

In practice however I don't really think it is redundant based on the discussion above. Although in the end it is a trade-off between saving 2 bytes of space or saving a few cycles on function call overhead, and a possible memory bus lock depending on the architecture and libc version etc.

It's possible to make valid arguments in all directions though, but in the end I think it's not really worth the trouble of changing it when no argument is really decisive.

**Comment by elfring** [comment]
Would you expect (or observe) that less null pointers will be passed than pointers for valid resources?

**Comment by rhuizer** [comment]
Fair, but then we go down the rabbit hole of having to review the code for use patterns of the pointers, considering the effects of branch prediction, possibly under using __builtin_expect, for the valid resource pointers and all the other stuff that follows ;P

I'm not saying either of the two is necessarily better than the other here, I'd have to investigate much more carefully, but that's not worth the effort. And lacking a convincing reason in either direction I'm not going to change things.

**Comment by elfring** [comment]
Would you eventually like to check by [the software “Coccinelle”](http://coccinelle.lip6.fr/ "Source code transformation with Coccinelle") (also with the help of a variant from the following script) if any update candidates will become more interesting?

```
@Remove_unnecessary_pointer_checks@
expression x;
@@
-if (\(x != 0 \| x != NULL\))
    free(x);
```
